sudo: required
git:
  depth: false
services:
- docker
language: node_js
node_js:
- '8'
before_install:
- git clone https://github.com/pkoniu/iosr-2017-deployment.git
- sh iosr-2017-deployment/before_install.sh
install:
- npm install
before_script:
- npm test
script:
- sh iosr-2017-deployment/script.sh
after_success:
- sh iosr-2017-deployment/after_success.sh
env:
  global:
  - DOCKER_USER=iosr2017
  - DOCKER_REPO=barista
  - HEROKU_APP_NAME=iosr2017barista
